aerostack2/aerostack2

.github/workflows/build-galactic.yaml, .github/workflows/build-humble.yaml, aerostack2/package.xml, as2_aerial_platforms/as2_aerial_platform/CMakeLists.txt, as2_aerial_platforms/as2_aerial_platform/package.xml, as2_aerial_platforms/as2_crazyflie_platform/package.xml, as2_aerial_platforms/as2_pixhawk_platform/as2_pixhawk_platform/package.xml, as2_aerial_platforms/as2_tello_platform/package.xml, as2_behaviors/movement_behaviors/follow_path/follow_path_plugin_base/package.xml, as2_behaviors/movement_behaviors/follow_path/follow_path_plugins/package.xml, as2_behaviors/movement_behaviors/go_to/goto_behaviour/package.xml, as2_behaviors/movement_behaviors/go_to/goto_plugin_base/package.xml, as2_behaviors/trajectory_generator/package.xml, as2_cli/CMakeLists.txt, as2_cli/package.xml, as2_controller/as2_controller_plugin_differential_flatness/package.xml, as2_controller/as2_controller_plugin_speed_controller/package.xml, as2_hardware_drivers/as2_hardware_drivers/CMakeLists.txt, as2_hardware_drivers/as2_hardware_drivers/package.xml, as2_hardware_drivers/as2_realsense_interface/package.xml, as2_motion_reference_handlers/package.xml, as2_simulation_assets/as2_simulation_assets/CMakeLists.txt, as2_simulation_assets/as2_simulation_assets/package.xml, as2_user_interfaces/alphanumeric_viewer/package.xml, as2_user_interfaces/as2_user_interface/CMakeLists.txt, as2_user_interfaces/as2_user_interface/package.xml, libs/pid_controller/package.xml
| Ticket(s) this addresses   | - |
---
* Create meta-packages for each aerostack folder 
* Aerostack package have all meta packages dependencies
* Fix as2_realsense package dependencies
* Add eigen dependencies
* Modify workflow to check aerostack package, which depend on all aerostack packages
* Aerial platform meta package not check ignition platform  and pixhawk platform, solve dependencies
* Simulation assets meta package not check ignition assets, neither gazebo assets
* Convert gazebo assets into a package
=> Pkg dependencies

as2_state_estimator/as2_state_estimator_plugin_mocap/CMakeLists.txt, as2_state_estimator/as2_state_estimator_plugin_mocap/include/state_estimator_plugin_mocap.hpp, as2_state_estimator/as2_state_estimator_plugin_mocap/package.xml, as2_state_estimator/as2_state_estimator_plugin_mocap/tests/plugin_test.cpp
---
| Issue(s) this addresses   | () |
| ROS2 version tested on | Galactic |
---
* mocap test converted into Gtest
* alpha value reduced to avoid huge delay in control loops
---
=> [as2_state_estimator_plugin_mocap] mocap test added to gtest and alpha reduced to 0.1

as2_python_api/package.xml
| Issue(s) this addresses   | #150  |
---
* Changed to apt package instead of pip, since pip package is not working properly on jenkins build (see #150)
=> [as2_python_api] Changed pymap3d to apt pkg

as2_simulation_assets/as2_ign_gazebo_assets/models/windmill/windmill.sdf, as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/bridges.py, as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/model.py
---
* Added debug model for visualize in rviz 
---
*  Right now debug pose stamped is hard-coded in ObjectModel
=> [as2_ign_gazebo_assets] Added debug model for visualize in rviz

as2_simulation_assets/as2_ign_gazebo_assets/launch/launch_simulation.py
---
| Issue(s) this addresses   | #208  |
---
* Change use sim time default value for ignition simulator.
* Use sim time in config file should be added to documentation
=> [ as2_simulation_assets] Use sim time default parameter

as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_aideck_stream_launch.py, as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_swarm_launch.py
| Aerial platform tested on | Crazyflie |
---
* Launch namespace was overriding each cf namespace
=> [as2_crazyflie_platform] Remove namespace from launch

as2_aerial_platforms/as2_platform_dji_osdk/src/dji_matrice_platform.cpp
---
| Issue(s) this addresses   | #298 |
| ROS2 version tested on | Humble, Galactic |
| Aerial platform tested on | DJI |
---
* Add a sleep to wait the take off finish by the DJI platform
=> [as2_platform_dji_osdk] Add take off sleep to wait until it has finished

as2_behaviors/as2_behaviors_motion/follow_reference_behavior/config/config_default.yaml, as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp, as2_behaviors/as2_behaviors_motion/go_to_behavior/config/config_default.yaml, as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_base.hpp, as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_behavior.hpp, as2_core/include/as2_core/utils/tf_utils.hpp, as2_core/src/utils/tf_utils.cpp
---
| Issue(s) this addresses   |#302 |
---
* Tf utils try_convert function admits timeout parameter
* Go to and follow reference behavior admits this timeout parameter
=> 302-Parametrize tf timeout in go to and follow reference behavior

as2_aerial_platforms/as2_platform_dji_osdk/include/dji_mop_handler.hpp
@javilinos please kindly review these changes. If merged update also `generadrone` branch to contain this.
---
* MOP links qos subscritions changed to reliable
=> [as2_platform_dji_osdk] Links qos subscritions changed to reliable

as2_aerial_platforms/as2_platform_dji_osdk/src/dji_matrice_platform.cpp, as2_behaviors/as2_behaviors_motion/CMakeLists.txt, as2_core/include/as2_core/sensor.hpp, as2_core/include/as2_core/utils/frame_utils.hpp, as2_core/include/as2_core/utils/tf_utils.hpp, as2_core/package.xml, as2_hardware_drivers/as2_realsense_interface/CMakeLists.txt, as2_hardware_drivers/as2_realsense_interface/include/as2_realsense_interface/as2_realsense_interface.hpp, as2_hardware_drivers/as2_realsense_interface/package.xml, as2_motion_controller/CMakeLists.txt, as2_motion_controller/package.xml, as2_motion_controller/plugins/differential_flatness_controller/include/differential_flatness_controller/differential_flatness_controller.hpp, as2_motion_controller/plugins/differential_flatness_controller/tests/controller_node.cpp, as2_motion_controller/plugins/pid_speed_controller/include/pid_speed_controller/pid_speed_controller.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/hover_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/position_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/speed_in_a_plane_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/speed_motion.hpp, as2_state_estimator/plugins/mocap_pose/include/mocap_pose.hpp
| Issue(s) this addresses   | #316 |
---
* Add dependency to `as2_core` package.xml
* Removed include from `as2_platform_dji_osdk`, `as2_behaviors_motion`, `as2_realsense_interface`, `as2_motion_controller`, `as2_state_estimator` and `as2_motion_reference_handlers`
* Using **.hpp** instead of **.h** library following deprecation warning suggestion
=> Only use tf2_geometry_msgs library when needed

as2_simulation_assets/as2_gazebo_classic_assets/scripts/run_sitl.sh
---
| Issue(s) this addresses   | #322 |
---
* if HEADLESS has a non-empty value then runs PX4 in the foreground, which stops the script from exiting
=> Runs PX4 in the foreground if gzclient is disabled (HEADLESS)

as2_motion_reference_handlers/include/as2_motion_reference_handlers/basic_motion_references.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/hover_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/position_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/speed_in_a_plane_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/speed_motion.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/trajectory_motion.hpp, as2_motion_reference_handlers/src/basic_motion_references.cpp, as2_motion_reference_handlers/src/hover_motion.cpp, as2_motion_reference_handlers/src/position_motion.cpp, as2_motion_reference_handlers/src/speed_in_a_plane_motion.cpp, as2_motion_reference_handlers/src/speed_motion.cpp, as2_motion_reference_handlers/src/trajectory_motion.cpp
| Issue(s) this addresses   | #329 |
---
* Namespace now can be given in the class constructor
=> Explicit namespace for motion reference handlers

as2_simulation_assets/as2_gazebo_classic_assets/package.xml, as2_simulation_assets/as2_gazebo_classic_assets/scripts/config.yaml
---
| Issue(s) this addresses   | #347  |
---
* Add gazebo_ros_pkgs dependence to make Gazebo been a ROS 2 node and publish `/clock` topic
=> [as2_gazebo_classic_assets] Add gazebo_ros_pkgs dependence

as2_simulation_assets/as2_gazebo_classic_assets/scripts/run_sitl.sh
---
| Aerial platform tested on | Gazebo 11, PX4 |
---
In the original file, it first checks if $world is a file; if it is, it continues with the directory part. However, during the second check with the -d parameter, it verifies the existence of a directory. Since $world is a file, this check will return false, assigning the address to "empty.world" and resulting in the launch of an empty world.
If only the directory is provided, appending only ".world" to the path will be incorrect. An approach to enable the addition of the world by specifying its absolute path could solve this problem.
"An example of how the .json file would be set up to launch the world.:
```python3
{
"world": …
```
=> Load custom world in gazebo 11

as2_core/include/as2_core/aerial_platform.hpp, as2_core/include/as2_core/names/topics.hpp, as2_core/src/aerial_platform.cpp, as2_motion_controller/include/as2_motion_controller/controller_handler.hpp, as2_motion_controller/src/controller_handler.cpp
---
| Aerial platform tested on | as2_multirotor_simulator |
---
* Now `as2_motion_controller` can bypass trajectory references and send them to `as2_aerial_platforms`
* Aerial platform now subscribe to trajectory commands
* Motion Controller and Aerial Platform topics and msg must be updated.
=> [as2_motion_controller] Add trajectory reference to actuators commands

as2_core/src/utils/tf_utils.cpp
Works on Galactic when timeout parameter is 0.
---
| Issue(s) this addresses   | #392 |
| ROS2 version tested on |Humble, Galactic|
| Aerial platform tested on |Gazebo, Crazyflie, DJI_OSDK|
---
* Timeout 0 parameter now works in Galactic
=> Bug fixed, getPoseStamped function differs from timeout 0 and not 0

as2_python_api/as2_python_api/tools/utils.py, as2_python_api/hooks/resource_paths.sh
| Issue(s) this addresses   | #402 |
---
* Hook links AS2_MODULES_PATH to `~/as2_ws/install/as2_python_api/share/as2_python_api/modules`, but sources are not installed when colcon building. The workaround is always looking at default as2 modules folder before looking at env var.
=> [as2_python_api] Jenkins test fail

as2_core/include/as2_core/utils/tf_utils.hpp, as2_core/src/utils/tf_utils.cpp
---
| Issue(s) this addresses   |#425 |
| Aerial platform tested on | None|
---
* get quaternion stamped included in tf utils
* Also fixed a typo in a parameter name in as2_motion_controller_manager
=> get quaternion stamped included in tf utils

as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
| Issue(s) this addresses   | (#421 ) |
| ROS2 version tested on | (Humble) |
| Aerial platform tested on | (Gazebo Fortress) |
---
This PR fixes issues with the existing crazyflie model not being able to fly and connects it up to the Aerostack2 api. 
Changes Crazyflie model names and plugins to mirror that of the quadcopter_base. 
It would be good to triple check it does work for others too. 
* Renamed the base_link of the crazyflie from `crazyflie/body` to `base_link`
* This is required as the motion_behaviour plugins seem to be hardcoded to`base_link` - see #421 for details 
* `static_update_frequency` of `ignition-gazebo-pose-publisher-system` increased to 100 as expected by controllers 
* …
=> [as2_gazebo_assets] Fix Crazyflie Model

as2_simulation_assets/as2_gazebo_assets/src/gimbal_bridge.cpp
---
| Issue(s) this addresses   | #431  |
---
* Added local frame to gimbal attitude and speed msgs
---
* Gimbal's displayed position frame is still incorrect, as it is relative to its initial position, it should be some kind of /gimbal/odom, but right now it is set asthe same as the speed.
=> Added local frame to simulated gimbal msg

as2_state_estimator/plugins/raw_odometry/config/default_state_estimator.yaml, as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
---
| Issue(s) this addresses   |#439|
| Aerial platform tested on | DJI_PSDK|
---
* User can decide z's component of earth to map transform 
* If user don't set it up, it correctly applies origin altitude - map altitude
=> As2 state estimator latlon2local function fails in z coordinate

as2_core/tests/CMakeLists.txt
---
---
* When using [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html) in `CMakeLists.txt`, paths are relative to the included `CMakeLists.txt`
* Adjust the path for the tests.
=> [as2_core] Fix adding as2_core tests

as2_motion_controller/src/controller_handler.cpp
---
| ROS2 version tested on | (Humble, Galactic, Other) |
| Aerial platform tested on | (Gazebo, Crazyflie, Tello, PX4, Other) |
---
* Publish speed limits when bypassing and control mode is Position, so the platform can use it
=> [as2_motion_controller_manager] Publish speed limits when bypassing and control mode is Position

as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
| Issue(s) this addresses   | #443  |
---
* Sensor name and payload were swapped while creating gz-ros bridge so gz-topic was wrong.
* From `/world/empty/model/drone0/model/hd_camera/link/hd_camera1/sensor/camera/image` to `/world/empty/model/drone0/model/hd_camera1/link/hd_camera/sensor/camera/image`. Notice that model name and link name was mixed.
=> [as2_gazebo_assets] Sensor model name and sensor link name were swapped in camera bridges

as2_behaviors/as2_behaviors_perception/detect_aruco_markers_behavior/src/detect_aruco_markers_behavior.cpp
| Issue(s) this addresses   | https://github.com/aerostack2/aerostack2/issues/508 |
---
cv::aruco::drawAxis has been [deprecated](https://github.com/opencv/opencv_contrib/commit/0f030dd0) on opencv-contrib 3.4.7/4.1.1 from Apri 2019 and [removed](https://github.com/opencv/opencv_contrib/commit/56d492cf) on 3.4.18/4.6.0 from Mar 17, 2022. Migrate the deprecated api to cv::drawFrameAxes.
Need to update dependency in release repo.
=> [as2_behaviors_perception] migrate deprecated api from cv::aruco::drawAxis to cv::drawFrameAxes

as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
| Issue(s) this addresses   | #569 |
---
* Launcher works now if no config file is given.
=> [as2_behaviors_motion] Not overwritting behavior config file if user config file is empty

as2_core/src/aerial_platform.cpp
---
| Issue(s) this addresses   | [#69](https://github.com/aerostack2/aerostack2.github.io/issues/69) |
---
* Don't call ownSendCommand until new ref arrives after control mode change
=> [as2_core] Don't call ownSendCommand until new ref arrives after control mode change

as2_aerial_platforms/as2_platform_gazebo/launch/platform_gazebo_launch.py
---
---
* Use sim time param default to true in launcher
=> [as2_platform_gazebo] Use sim time true by default in gazebo platform

as2_state_estimator/plugins/ground_truth/include/ground_truth.hpp
---
| Issue(s) this addresses   | #615 |
---
* Ground truth plugin generates map at drone initial position
=> [as2_state_estimator] map generates at the drone initial position

as2_core/include/as2_core/sensor.hpp
---
---
* Make SensorData inheritance public to access getData and getTopicName when using as2_sensors
=> [as2_core] Make SensorData public to access getData and getTopicName

as2_hardware_drivers/as2_usb_camera_interface/tests/as2_usb_camera_interface_gtest.cpp, as2_state_estimator/tests/as2_state_estimator_gtest.cpp
---
---
* Fix gtest warning: 
`[WARN] [1723143702.107190823] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.`
=> [aerostack2] Fix gtest warning: publisher already registered

as2_core/src/aerial_platform.cpp
---
---
* Enable `ownSendCommand` when `Hover`, as no reference is expected
=> [as2_core] In as2_aerial_platform enable ownSendCommand when Hover

as2_simulation_assets/as2_gazebo_assets/README.md, as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/hexrotor_base/hexrotor_base.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/magnetometer/magnetometer.sdf, as2_simulation_assets/as2_gazebo_assets/models/magnetometer/model.config, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/x500/x500.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
---
---
* Set magnetometer sensor by user instead of default sensor.
To add sensor, must be defined in world config file as:
```
world_name: "empty"
drones:
- model_type: "quadrotor_base"
model_name: "drone0"
xyz:
- 0.0
- 0.0
- 0.3
payload:
- model_type: "magnetometer"
model_name: "magnetometer"
```
=> [as2_gazebo_assets] Set magnetometer sensor by user instead of default sensor

as2_simulation_assets/as2_gazebo_assets/README.md, as2_simulation_assets/as2_gazebo_assets/models/air_pressure/air_pressure.sdf, as2_simulation_assets/as2_gazebo_assets/models/air_pressure/model.config, as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/hexrotor_base/hexrotor_base.sdf, as2_simulation_assets/as2_gazebo_assets/models/hexrotor_base/hexrotor_base.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base_viz.sdf, as2_simulation_assets/as2_gazebo_assets/models/x500/x500.sdf, as2_simulation_assets/as2_gazebo_assets/models/x500/x500.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/x500/x500_viz.sdf, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py, as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
---
---
* Set air pressure sensor by user instead of default sensor.
* Fix air pressure sdf format.
To add sensor, must be defined in world config file as:
```
world_name: "empty"
drones:
- model_type: "quadrotor_base"
model_name: "drone0"
xyz:
- 0.0
- 0.0
- 0.3
payload:
- model_type: "air_pressure"
model_name: "air_pressure"
```
=> [as2_gazebo_assets] Set air pressure sensor by user instead of default sensor

as2_map_server/CMakeLists.txt, as2_map_server/package.xml, as2_map_server/plugins.xml, as2_map_server/plugins/depth2occ_grid/CMakeLists.txt, as2_map_server/plugins/depth2occ_grid/config/plugin_default.yaml, as2_map_server/plugins/depth2occ_grid/launch/depth2occ_grid-map_server.launch.py, as2_map_server/plugins/mapping_2d/CMakeLists.txt, as2_map_server/plugins/mapping_2d/launch/mapping_2d-map_server.launch.py, as2_map_server/plugins/mapping_2d/src/mapping_2d.cpp
---
* Added new plugin `depth2occ_grid`. New plugin is a zero-code plugin. It only contains launcher and config file. It consists of an input adaptation (`depthimage_to_laserscan` from `ros-perception`) and the `map_server` running with `mapping_2d` plugin.
* CMakeLists structure changed to build plugin libraries from each plugin CMake.
* Created generic launcher and specific launcher at each plugin. The generic one just includes the launcher of the plugin selected.
* Bug on `mapping_2d` plugin fixed when scan range is NaN.
* New entry in documentation explaining the map server and its plugins
---
* Rename `mapping_2d` …
=> [as2_map_server] New depth image to occupancy grid plugin

as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp, as2_core/include/as2_core/aerial_platform.hpp, as2_core/src/aerial_platform.cpp, as2_core/tests/mocks/aerial_platform/mock_aerial_platform.cpp, as2_core/tests/mocks/aerial_platform/mock_aerial_platform.hpp, as2_motion_controller/include/as2_motion_controller/controller_base.hpp, as2_motion_controller/include/as2_motion_controller/controller_handler.hpp, as2_motion_controller/plugins/differential_flatness_controller/include/differential_flatness_controller/differential_flatness_controller.hpp, as2_motion_controller/plugins/differential_flatness_controller/src/differential_flatness_controller.cpp, as2_motion_controller/plugins/pid_speed_controller/include/pid_speed_controller/pid_speed_controller.hpp, as2_motion_controller/plugins/pid_speed_controller/src/pid_speed_controller.cpp, as2_motion_controller/src/controller_handler.cpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/basic_motion_references.hpp, as2_motion_reference_handlers/include/as2_motion_reference_handlers/trajectory_motion.hpp, as2_motion_reference_handlers/src/basic_motion_references.cpp, as2_motion_reference_handlers/src/trajectory_motion.cpp, as2_msgs/msg/TrajectoryPoint.msg, as2_msgs/msg/TrajectorySetpoints.msg
---
---
* Motion references and actuators command use TrajectorySetpoints.msg, with an array of TrajectoryPoint.msg
=> [aerostack2] Convert trajectory references into an array of references

as2_aerial_platforms/as2_platform_gazebo/src/as2_platform_gazebo_node.cpp, as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator_node.cpp, as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior_node.cpp, as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface_node.cpp, as2_hardware_drivers/as2_usb_camera_interface/src/as2_usb_camera_interface_node.cpp, as2_motion_controller/src/controller_manager_node.cpp, as2_state_estimator/src/as2_state_estimator_node.cpp
---
---
* By default, ROS 2 set the node frequency.
* User can set one by using the `node_frequency` param
* Set this change in:
1. as2_platform_gazebo
2. as2_platform_multirotor_simulator
3. as2_motion_controller
4. as2_state_estimator
5. as2_behaviors_trajectory_generation
* Add and test this on rest of packages
=> [aerostack2] Use as2::spingLoop without preset_loop_frequency

as2_behaviors/as2_behaviors_motion/takeoff_behavior/plugins/takeoff_plugin_trajectory.cpp
---
---
* Set takeoff behavior with trajectory yaw mode to Keep Yaw
=> [as2_behaviors_motion] Fix takeoff behavior with trajectory yaw mode to Keep Yaw

as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
| Issue(s) this addresses   | #698, #689 |
---
* Fix jinja env dir when model comes from outside aerostack2
* Jinja2 env dir is now grandparent from model
* Valid drone model_type can be extended with AS2_EXTRA_DRONE_MODELS environment variable
* Update documentation on how to add a new drone model
---
-
=> [as2_gazebo_assets] Fix jinja env dir when model comes from outside aerostack2

as2_aerial_platforms/as2_platform_gazebo/launch/platform_gazebo_launch.py
| Issue(s) this addresses   | #701  |
---
* Launch argument `create_bridges` to whether or not create platform bridges
=> [as2_platform_gazebo] New launch argument to disable bridges creation

as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/gimbal/position_gimbal.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/gimbal/speed_gimbal.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/px4vision/px4vision.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja, as2_simulation_assets/as2_gazebo_assets/models/x500/x500.sdf.jinja
---
* Jinja environment path was changed in #699, so hardcoded path in gimbals couldn't find model files for gimbals and cameras
* Models attached to gimbals are hardcoded in jinja templates. This have to be documented somewhere
---
* Models attached to gimbals are hardcoded in jinja templates. This is a really bad idea, we should think in a better way of doing this.
=> [as2_gazebo_assets] Fix path to gimbals and camera sensors

as2_aerial_platforms/as2_platform_gazebo/include/as2_platform_gazebo/as2_platform_gazebo.hpp, as2_aerial_platforms/as2_platform_gazebo/src/as2_platform_gazebo.cpp, as2_core/include/as2_core/aerial_platform.hpp, as2_core/src/aerial_platform.cpp
| Issue(s) this addresses   | #706 |
---
* FSM in Gazebo platform can be reset.
* Reset implementation follows these steps:
* FSM --> LAND
* FSM --> LANDED
* disarm()
* armed --> false
* offboard --> false
* FSM --> DISARMED
=> [as2_platform_gazebo] Reset FSM

as2_behaviors/as2_behaviors_motion/follow_reference_behavior/src/follow_reference_behavior.cpp
---
---
* Remove rclcpp info of yaw mode in each iteration
=> [as2_behaviors_motion] In follow reference, remove rclcpp info of yaw mode in each iteration

as2_core/tests/mocks/CMakeLists.txt
Error when linking using clang
---
| Issue(s) this addresses   | (add issues here #749 ) |
---
See #749
=> [fix] add as2_core to dependencies in mock lib

as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml, as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp, as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp, as2_msgs/msg/YawMode.msg, as2_python_api/as2_python_api/modules/trajectory_generation_module.py
---
| Aerial platform tested on |  Multirotor Simulator |
---
* Parameter path_lenght to generate the trajectory in partial trajectory. ( 0 is full trajectory)
* Change the method goalToDynamicWaypoint to work with queues instead of vectors
* New mode FACE_REFERENCE add in the YawMode message
* New method computeYawReference to face the next reference during trajectory
* New method traj_generation_with_face_reference in the module trajectory_generation_module from the modules of the as2_python_api to access to the new yaw mode from the mission
*Fixed exception when there are still waypoints to reach but the trajectory generator has finished
=> [as2_behaviors_trajectory_generation] Generate partial trajectory and new yaw to face the next refernce

as2_aerial_platforms/as2_platform_multirotor_simulator/CMakeLists.txt, as2_aerial_platforms/as2_platform_multirotor_simulator/config/world_config.yaml, as2_aerial_platforms/as2_platform_multirotor_simulator/include/as2_platform_multirotor_simulator/as2_interface.hpp, as2_aerial_platforms/as2_platform_multirotor_simulator/include/as2_platform_multirotor_simulator/as2_platform_multirotor_simulator.hpp, as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_interface.cpp, as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp, as2_aerial_platforms/as2_platform_multirotor_simulator/tests/as2_platform_multirotor_simulator_fly_gtest.cpp
---
---
Aerostack2 uses: earth_{as2} - map_{as2} - odom_{as2} - base_link_{as2}
MultirotorS uses: earth_{mrs} - map_{mrs} - odom_{mrs} - base_link_{mrs}
We expect: 
- earth_{as2} = earth_{mrs}
- odom_{as2} = odom_{mrs}
So:
- Publish ground truth and odometry reading earth_{mrs} and odom_{mrs}
- Convert commands from odom_{as2} to earth_{mrs} (when using grount_truth for control) or to odom_{mrs} (when using odometry for control)
If the condition is not met, position, velocity and trajectory commands will not work.
* Explain this in documentation
---
* Test GPS missions
* Improve simulation frames and …
=> [as2_platform_multirotor_simulator] Use as2 interface to convert commands and states

as2_behavior_tree/src/as2_behavior_tree_node.cpp
---
| Issue(s) this addresses   | ([#14](https://github.com/aerostack2/project_gazebo/issues/14)) |
| ROS2 version tested on | (Humble) |
| Aerial platform tested on | (Gazebo) |
---
Introduced a new parameter wait_for_service_timeout with a default value of 5000 milliseconds.
This prevents the crashing:
[as2_behavior_tree_node-1] terminate called after throwing an instance of 'BT::RuntimeError'
[as2_behavior_tree_node-1]   what():  Blackboard::get() error. Missing key [wait_for_service_timeout]
---
=> [as2_behavior_tree] Add wait_for_service_timeout parameter

as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml, as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp, as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
---
| Issue(s) this addresses   | -|
---
* Update the updateFrame method to use the new method from the dynamic_trajectory_generator library, which allows modifying a set of waypoints with a single call.
* The computeErrorFrames method, which calls the updateFrame, is invoked by a new timer outside of the stateCallback.
* The frequency of the new timer is a parameter set via the config file.
*The default value of the frequency is 0, which disables the timer callback.
*Synchronize the plotTrajectoryThread with the updateFrame
=> [as2_behaviors_trajectory_generator] Modify a set of waypoints due to frame offsets

as2_behaviors/as2_behaviors_swarm_flocking/package.xml
| Issue(s) this addresses   | #813 |
---
* `eigen` dependency
* Change to cvar-upm maintainer
=> [as2_behaviors_swarm_flocking] ROS buildfarm dependency fix
