aerostack2/aerostack2

- as2_python_api/python_interface/python_interface/modules/motion_reference_handler_module.py
| Ticket(s) this addresses   | #7  |
---
* Added missing parent to MotionReferenceHandlerModule #7
> [as2_python_interface] Added missing parent

- as2_aerial_platforms/as2_ignition_platform/launch/ignition_platform_launch.py
- as2_behaviors/movement_behaviors/go_to/goto_plugins/src/goto_plugin_position.cpp
- as2_behaviors/movement_behaviors/land/land_plugins/src/land_plugin_speed.cpp
- as2_python_api/python_interface/python_interface/modules/follow_path_module.py
| Ticket(s) this addresses   | - |
| Aerial platform tested on | Ignition, PX4 |
---
* Fix as2_ignition_platform launcher package name.
* Fix goto plugin position yaw management.
* Improve land plugin speed goal condition.
* Python interface follow path with keep yaw name fix.
> Small fix names

- as2_cli/bash_utils/as2_autocompletion.bash
- as2_cli/bash_utils/as2_cd.bash
* stack folder has been removed from as2 list and as2 cd commands
* as2 cd now support not adding 'as2_' prefix
> Improve cli

- as2_cli/bash_utils/as2_test.bash
* Verbose argument added to $as2 test --verbose or -v
> added verbose mode to as2 test

- as2_msgs/CMakeLists.txt
- as2_msgs/msg/Alert.msg
- as2_msgs/msg/Geofence.msg
Alert.msg removed from Cmakelist.txt
Alert.msg file removed from msg folder.
Modified geofence.msg.
> old geofencing alert deleted, new type field in geofence msg

- as2_aerial_platforms/as2_crazyflie_platform/launch/aideck_stream_launch.py
- as2_aerial_platforms/as2_crazyflie_platform/launch/crazyflie_platform_launch.py
- as2_aerial_platforms/as2_crazyflie_platform/launch/crazyflie_platform_with_aideck_launch.py
- as2_aerial_platforms/as2_crazyflie_platform/launch/crazyflie_swarm_launch.py
---
| Ticket(s) this addresses   | - |
---
* Update package name and node name to as2_crazyflie_platform
> Update package and node name

- as2_user_interfaces/keyboard_teleoperation/package.xml
---
* Change package.xml  motion_reference_handlers depend to as2_motion_reference_handlers
> Update package motion handlers

- as2_behavior_trees/README.md
| Issue(s) this addresses   | #37  |
| ROS2 version tested on | - |
---
* Added index
* Added details dropbox
* Added missing nodes
* Added "How to create new nodes?"
---
* Improve developer configuration
> [as2_behavior_trees] Documentation improved

- as2_hardware_drivers/as2_realsense_interface/include/as2_realsense_interface/as2_realsense_interface.hpp
- as2_hardware_drivers/as2_realsense_interface/package.xml
- as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface.cpp
---
| ROS2 version tested on | Galactic |
---
* Changed realsense2 dependency to librealsense2
---
> Solve as2_realsense_interface dependecy problem

- .github/workflows/build-galactic.yaml
- .github/workflows/build-humble.yaml
- codecov.yaml
- codecov.yml
> try to add code coverage

- as2_aerial_platforms/as2_crazyflie_platform/src/crazyflie_platform.cpp
- as2_controller/as2_controller_plugin_differential_flatness/tests/plugin_test.cpp
| ROS2 version tested on | - |
---
* Clang test fixed
> [CI] Clang format fixed

- as2_motion_reference_handlers/as2_motion_reference_handlers/basic_motion_references.py
- as2_python_api/python_interface/examples/motion_reference.py
---
* Make two method privates
* Add python example
> Make controller_info_callback and __set_mode privates

- as2_aerial_platforms/as2_tello_platform/test/main.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/behavior_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/localization_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/package.xml
- as2_user_interfaces/as2_user_interface/package.xml
---
| ROS2 version tested on | (Humble, Galactic, Other) |
| Aerial platform tested on | (Ignition, Crazyflie, Tello, PX4, Other) |
---
---
> python interface substituted by as2_python_api

- as2_hardware_drivers/as2_usb_camera_interface/include/as2_usb_camera_interface/as2_usb_camera_interface.hpp
---
| ROS2 version tested on | Galactic |
---
* Removed opencv2/aruco.hpp from as2_usb_camera_interface.hpp
---
> Dependency removed

- .github/workflows/build-galactic.yaml
- .github/workflows/build-humble.yaml
- .gitmodules
- as2_aerial_platforms/as2_aerial_platform/package.xml
- as2_aerial_platforms/as2_pixhawk_platform/.clang-format
- as2_aerial_platforms/as2_pixhawk_platform/CMakeLists.txt
- as2_aerial_platforms/as2_pixhawk_platform/include/as2_pixhawk_platform/pixhawk_platform.hpp
- as2_aerial_platforms/as2_pixhawk_platform/package.xml
- as2_aerial_platforms/as2_pixhawk_platform/src/pixhawk_platform.cpp
---
* Remove px4 ros com dependency
* Get px4_msgs from git submodule
> [as2_pixhawk_platform] Remove px4 ros com dependency

- as2_behaviors/as2_aruco_detector/CMakeLists.txt
- as2_behaviors/as2_aruco_detector/package.xml
---
| ROS2 version tested on | Galactic|
---
* Added opencv & opencv_libs to CMakeLists.txt
---
> Added opencv lib

- .github/workflows/build-galactic.yaml
- .github/workflows/build-humble.yaml
- .github/workflows/codecov_test.yaml
- .gitignore
- .gitmodules
- dependency_repos.repos
---
| ROS2 version tested on | (Humble, Galactic, Other) |
| Aerial platform tested on | (Ignition, Crazyflie, Tello, PX4, Other) |
---
---
> Remove px4 submodule

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/behavior_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
---
| Issue(s) this addresses   | Right-left changed |
| Aerial platform tested on | Ignition|
---
* Right left values inverted for pose and speed mode.
* Removed attitude mode button.
* Added and tested behavior control (pause and resume).
* Now reads behaviors from status variable of drone interfaces.
---
* Add a configuration file.
* Test behavior control with more than one behavior executing at once.
> Fix update as2 keyboard teleoperation

- as2_simulation_assets/as2_ign_gazebo_assets/src/ground_truth_bridge.cpp
| Issue(s) this addresses   | #123 |
---
* Moved ros publishers creation before ign subscriber
> Ground truth bridge segmentation fault fix

- as2_user_interfaces/as2_alphanumeric_viewer/include/as2_alphanumeric_viewer/alphanumeric_viewer.hpp
- as2_user_interfaces/as2_alphanumeric_viewer/src/alphanumeric_viewer.cpp
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/localization_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
---
| Issue(s) this addresses   | #128  #129|
---
* Fix crash when selecting drone while behavior window is active.
* Changed drone_id for namespace in launch parameters.
* Localization window bigger.
---
* Add shortcuts (WIP)
* Add confirmation dialogs
* Limit max values
* Ability to parametrize values without compilation (WIP)
> Hot fix keyboard teleoperation + parameter namespace

- as2_user_interfaces/as2_alphanumeric_viewer/include/as2_alphanumeric_viewer/alphanumeric_viewer.hpp
- as2_user_interfaces/as2_alphanumeric_viewer/src/alphanumeric_viewer.cpp
---
| Issue(s) this addresses   |Add summary window|
| ROS2 version tested on |Humble |
---
Add summary window. It contains:
* namespace
* platform status (all)
* battery
* self localization
* control mode (platform, controller)
* IMU
---
* Add color code
> summary window added to alphanumeric viewer

- as2_core/src/platform_state_machine.cpp
- as2_core/tests/platform_state_machine_test.cpp
---
* Fix platform state machine service response.
* Add platform state machine tests.
> [as2_core] Fix platform state machine callback response

- as2_core/CMakeLists.txt
- as2_core/include/as2_core/names/services.hpp
- as2_python_api/as2_python_api/behavior_actions/followpath_behavior.py
- as2_python_api/as2_python_api/behavior_actions/goto_behavior.py
- as2_python_api/as2_python_api/modules/follow_path_gps_module.py
- as2_python_api/as2_python_api/modules/gps_module.py
- as2_python_api/as2_python_api/test/gps/fake_origin_server.py
- as2_python_api/as2_python_api/test/gps/origin_gps.py
- as2_python_api/package.xml
- as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
- as2_state_estimator/plugins/external_odom/config/default_state_estimator.yaml
- as2_state_estimator/plugins/external_odom/include/external_odom.hpp
| Issue(s) this addresses   | #71 |
---
* **[state_estimator]** Origin srvs added to state_estimator external_odom plugin
* **[as2_names]** Added default get and set origin srvs
* **[as2_core]** Added missing dependency geographiclib
* **[as2_python_api]** Origin in gps module
* **[as2_python_api]** Fixed goto and follow path for gps
* **[as2_python_api]** new gps tests
* **[as2_python_api]** new dependency [pymap3d](https://github.com/geospace-code/pymap3d)
---
* Refactor state estimator to move out origin srvs to the as2 node
* Review if new dependency (pymap3d) is really needed or can be changed with a lighter one
> GPS behavior support

- aerostack2/package.xml
| Issue(s) this addresses   | #138 |
---
* Remove as2_behaviors metapackage from aerostack/package.xml
> Remove as2_behaviors metapackage

- as2_python_api/as2_python_api/behavior_actions/followpath_behavior.py
- as2_python_api/as2_python_api/behavior_actions/goto_behavior.py
- as2_python_api/as2_python_api/modules/follow_path_gps_module.py
| Issue(s) this addresses   | #141 |
---
* Float conversion at goto and followpath behaviors
* Adding list to Follow path GPS arguments
* GPS behaviors now uses height to origin
> Height to origin, float casting and follow_path_gps list argument

- as2_aerial_platforms/as2_platform_dji_osdk/package.xml
- as2_aerial_platforms/as2_platform_tello/package.xml
| Issue(s) this addresses   | #148 |
| ROS2 version tested on | - |
---
* Updated license, maintainers and description for dji and tello platforms package.xml
> Updated liceses and description

- as2_python_api/as2_python_api/modules/follow_path_gps_module.py
---
* Fix follow path gps units convertion, from list to GeoPath
> [as2_python_api] Fix follow path gps convertion

- as2_simulation_assets/as2_ign_gazebo_assets/worlds/empty.sdf
---
* Add GPS coordinates to empty world
> [as2_ign_gazebo_assets] Add GPS coordinates to empty world

- as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_speed.cpp
- as2_behaviors/as2_behaviors_motion/launch/land_behavior_launch.py
| Issue(s) this addresses   | #175 |
---
* Declared missing parameters in plugin cpp
* Added parameter to land standalone behavior launch
* Added description to launch arguments
* Automatic listing of available plugins
* Extend automatic listing of available plugins to other behaviors and packages
> Loading parameters in land behavior fixed

- as2_behaviors/as2_behaviors_trajectory_generation/CMakeLists.txt
---
| Issue(s) this addresses   | ( #153) |
| ROS2 version tested on | (Galactic) |) |
---
* Extra foreach removed in CMakeLists.txt
> [bug] extra foreach removed

- as2_python_api/as2_python_api/modules/test_module.py
| Issue(s) this addresses   | #177 |
---
* New test module
> New Test Module

- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/modules/follow_path_gps_module.py
- as2_python_api/as2_python_api/modules/go_to_gps_module.py
- as2_python_api/as2_python_api/test/modules/test_recursive_modules.py
- as2_python_api/as2_python_api/tools/utils.py
| Issue(s) this addresses   | #180 |
---
* improved `load_module()` method, see [docs](https://docs.python.org/3.10/library/importlib.html#importing-programmatically)
* `load_module()` now only loads a module if it isn't already loaded
* module `__deps__` attribute list its module dependencies
* `load_module()` try to load all module dependencies too
* `go_to_gps` new dependency `gps`
* `follow_path_gps` new dependency `gps`
* New load recursive test
> Module dependencies and recursive loading modules

- as2_python_api/as2_python_api/test/modules/test_drone_interfaces.py
- as2_python_api/as2_python_api/test/modules/test_recursive_modules.py
| Issue(s) this addresses   | #184 |
---
* Shutting down context in python tests
> Shutting down context in python test

- as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_swarm_launch.py
- as2_aerial_platforms/as2_platform_crazyflie/scripts/aideck_node.py
---
---
* Clean cf launcher, removing unused parameters
> Clean launcher parameters

- as2_python_api/as2_python_api/behavior_manager/behavior_manager.py
---
| Issue(s) this addresses   | #182 |
| Aerial platform tested on |Ignition |
---
* Multithreading applied now when managing 'all_behaviors' functions.
---
> behavior manager __all_behaviors functions paralelized for swarm

- as2_behaviors/as2_behaviors_motion/CMakeLists.txt
- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/src/follow_reference_behavior_main.cpp
- as2_behaviors/as2_behaviors_motion/launch/follow_reference_behavior_launch.py
- as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
- as2_msgs/CMakeLists.txt
- as2_msgs/action/FollowReference.action
- as2_python_api/as2_python_api/behavior_actions/follow_reference_behavior.py
- as2_python_api/as2_python_api/drone_interface.py
- as2_python_api/as2_python_api/modules/follow_reference_module.py
---
| Issue(s) this addresses   | Follow reference persistent |
| Aerial platform tested on | Ignition|
---
* Added new behavior follow reference in behavior_motion section 
* Added new client in as2_python_api with two basics functions, follow reference with keep yaw and follow reference with fixed yaw (relative to the reference).
* Added new behavior follow reference alongside others.
---
* Pluguinize the behavior, move what is implemented now to position_plugin and add trajectory_plugin in case we want to execute a fixed trajectory relative to a frame or moving frame.
> Add follow reference behavior

- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
- as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
---
| Issue(s) this addresses   | #196  |
---
* Remove follow reference from general motion behaviors launch
* Change as2 launch in projects where follow reference is used
> [as2_behaviors_motion] Follow Reference Behavior Transforms Error

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/settings_window.py
---
| Issue(s) this addresses   |Remove attitude code|
---
* Remove all traces of code of attitude mode
* Change settings image
---
> [as2_keyboard_teleoperation] remove everything related to attitude mode

- as2_msgs/CMakeLists.txt
- as2_msgs/package.xml
| Issue(s) this addresses   | #205 |
---
* Added `action_msgs` dependency to as2_msgs
> Added action_msgs dependency

- as2_motion_controller/src/controller_manager.cpp
---
| Issue(s) this addresses   | #207  |
---
* Fix freq parameter names
> [as2_controller_manager] Fill info message

- as2_simulation_assets/as2_ign_gazebo_assets/launch/launch_simulation.py
- as2_simulation_assets/as2_ign_gazebo_assets/launch/object_bridges.py
- as2_simulation_assets/as2_ign_gazebo_assets/launch/world_bridges.py
| Issue(s) this addresses   | #221 |
---
* Added GUI config file
* Some new documenting
> [as2_ign_gazebo_assets] Added GUI config file

- aerostack2/package.xml
- as2_aerial_platforms/as2_platform_crazyflie/package.xml
- as2_aerial_platforms/as2_platform_dji_osdk/package.xml
- as2_aerial_platforms/as2_platform_ign_gazebo/package.xml
- as2_aerial_platforms/as2_platform_tello/package.xml
- as2_behavior_tree/package.xml
- as2_behaviors/as2_behavior/package.xml
- as2_behaviors/as2_behaviors_motion/package.xml
- as2_behaviors/as2_behaviors_perception/package.xml
- as2_behaviors/as2_behaviors_platform/package.xml
- as2_behaviors/as2_behaviors_trajectory_generation/package.xml
- as2_cli/package.xml
- as2_core/package.xml
- as2_hardware_drivers/as2_realsense_interface/package.xml
- as2_hardware_drivers/as2_usb_camera_interface/package.xml
- as2_motion_controller/package.xml
- as2_motion_reference_handlers/package.xml
- as2_msgs/package.xml
- as2_python_api/package.xml
- as2_python_api/setup.py
- as2_simulation_assets/as2_gazebo_classic_assets/package.xml
- as2_simulation_assets/as2_ign_gazebo_assets/package.xml
- as2_state_estimator/package.xml
- as2_user_interfaces/as2_alphanumeric_viewer/package.xml
- as2_user_interfaces/as2_keyboard_teleoperation/package.xml
- as2_user_interfaces/as2_keyboard_teleoperation/setup.py
| Issue(s) this addresses   | #200 |
| ROS2 version tested on | (Humble, Galactic,  |
---
* Maintainer unified to CVAR-UPM
> Maintainer unified to CVAR-UPM

- as2_motion_controller/launch/controller_launch.py
- as2_motion_controller/plugins/differential_flatness_controller/include/differential_flatness_controller/differential_flatness_controller.hpp
- as2_motion_controller/plugins/differential_flatness_controller/src/differential_flatness_controller.cpp
- as2_motion_controller/plugins/differential_flatness_controller/tests/plugin_test.cpp
---
| Issue(s) this addresses   | #226  |
---
* Fix namespace of the differential_flatness_controller plugin
> [as2_motion_controller] Fix failed to load differential_flatness_controller

- as2_msgs/CMakeLists.txt
- as2_msgs/msg/MissionUpdate.msg
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
- as2_simulation_assets/as2_ign_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf
| Issue(s) this addresses   | #187 |
| Aerial platform tested on | Ignition, Crazyflie |
---
* Added new message MissionUpdate
* Append and insert element in mission stack
* Reset mission
> [as2_python_api] Mission updates: reset, append and insert

- as2_motion_reference_handlers/as2_motion_reference_handlers/basic_motion_references.py
---
| Issue(s) this addresses   | #259  |
---
* Change JointTrajectoryPoint to TrajectoryPoint msg type
> [as2_motion_reference_handlers] Change JointTrajectoryPoint to TrajectoryPoint msg type

- as2_simulation_assets/as2_ign_gazebo_assets/models/aruco_gate_1/aruco_gate_1.sdf
- as2_simulation_assets/as2_ign_gazebo_assets/models/aruco_gate_2/aruco_gate_2.sdf
---
| Issue(s) this addresses   | Add position plugin to gates |
---
* Added position plugin to gates
> added position plugin to gates

- as2_python_api/as2_python_api/modules/go_to_module.py
---
| Issue(s) this addresses   |Add frame_id argument to go_to|
---
* Added frame_id argument to go_to simplifications
> added frame_id argument to go_to

- as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_behavior.hpp
- as2_python_api/as2_python_api/behavior_actions/followpath_behavior.py
- as2_python_api/as2_python_api/modules/follow_path_module.py
---
| Issue(s) this addresses   |frame_id not working|
> follow path frame bug fixed, frame id argument added to python interface

- as2_motion_controller/include/as2_motion_controller/controller_base.hpp
- as2_motion_controller/plugins/differential_flatness_controller/include/differential_flatness_controller/differential_flatness_controller.hpp
- as2_motion_controller/plugins/differential_flatness_controller/src/differential_flatness_controller.cpp
- as2_motion_controller/plugins/pid_speed_controller/include/pid_speed_controller/pid_speed_controller.hpp
- as2_motion_controller/plugins/pid_speed_controller/src/pid_speed_controller.cpp
- as2_motion_controller/src/controller_handler.cpp
- as2_motion_controller/src/controller_manager.cpp
---
| Issue(s) this addresses   | #274  |
---
* `updateParams` now pass a rclcpp parameter for plugin to read param value from there
* Update motion controller plugin guide
> [as2_motion_controller] Change updateParams input from std::string to rclcpp::Parameter

- as2_msgs/msg/YawMode.msg
---
| Issue(s) this addresses   |#276|
---
* Added new yaw mode frame facing
* Include new yaw mode
> new yaw mode yaw to frame added

- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
- as2_msgs/msg/YawMode.msg
- as2_python_api/as2_python_api/modules/follow_reference_module.py
---
| Issue(s) this addresses   | #272 |
---
* Follow reference now admits reference facing mode.
* New yaw mode: REFERENCE_FACING
---
> follow reference with reference facing added

- as2_simulation_assets/as2_ign_gazebo_assets/models/windmill/windmill.sdf
- as2_simulation_assets/as2_ign_gazebo_assets/src/azimuth_bridge.cpp
- as2_simulation_assets/as2_ign_gazebo_assets/worlds/empty_gps.sdf
---
| Issue(s) this addresses   | #229|
---
* Earth frame aligned to ENU
> Change 0 deg reference from North to East

- as2_behaviors/as2_behaviors_motion/launch/follow_path_behavior_launch.py
- as2_behaviors/as2_behaviors_motion/launch/go_to_behavior_launch.py
- as2_behaviors/as2_behaviors_motion/launch/land_behavior_launch.py
- as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
- as2_behaviors/as2_behaviors_motion/launch/takeoff_behavior_launch.py
- as2_motion_controller/launch/controller_launch.py
- as2_python_api/as2_python_api/behavior_manager/behavior_manager.py
- as2_python_api/as2_python_api/mission_interpreter/mission.py
- as2_simulation_assets/as2_ign_gazebo_assets/launch/launch_simulation.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/drone.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/object.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/payload.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/world.py
---
| Issue(s) this addresses   | #285  |
---
* Changed list to List when stating return types and function parameter types to support Python3.8.
> Changed typing list to List

- as2_simulation_assets/as2_ign_gazebo_assets/launch/object_bridges.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/gps_bridge.cpp
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/bridges/custom_bridges.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/object.py
---
| Issue(s) this addresses   | #300|
| Aerial platform tested on | Ignition|
---
* GPS_Bridge module now use use_sim_time parameter to decide which clock to publish on
> use_sim_time now works in gps bridge

- as2_simulation_assets/as2_ign_gazebo_assets/models/quadrotor_base/quadrotor_base_viz.sdf
---
* Added new quadrotor base model for proper visualization in rviz2
> Added drone_viz sdf

- as2_aerial_platforms/as2_platform_dji_osdk/CMakeLists.txt
- as2_aerial_platforms/as2_platform_dji_osdk/config/mop_handler_config_file.yaml
- as2_aerial_platforms/as2_platform_dji_osdk/config/platform_config_file.yaml
- as2_aerial_platforms/as2_platform_dji_osdk/include/dji_matrice_platform.hpp
- as2_aerial_platforms/as2_platform_dji_osdk/include/dji_mop_handler.hpp
- as2_aerial_platforms/as2_platform_dji_osdk/launch/as2_platform_dji_osdk_launch.py
- as2_aerial_platforms/as2_platform_dji_osdk/src/dji_matrice_platform.cpp
- as2_aerial_platforms/as2_platform_dji_osdk/src/dji_mop_handler.cpp
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
- as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
| Aerial platform tested on | DJI OSDK |
---
* New MOP channel
* Collateral mission control bug fixing
> [as2_platform_dji_osdk] Mop channel communication

- as2_python_api/as2_python_api/behavior_actions/behavior_handler.py
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
- as2_python_api/as2_python_api/mission_interpreter/mission_stack.py
---
* Behavior stop also working while paused
* Added MissionStack str method
* Mission Interpreter resume not blocking execution
> Some Mission Control fixes

- as2_simulation_assets/as2_ign_gazebo_assets/launch/drone_bridges.py
- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/payload.py
| Issue(s) this addresses   | #313 |
---
* Fixing payload bridges
> Payload bridges fix

- as2_aerial_platforms/as2_platform_dji_osdk/package.xml
- as2_behaviors/as2_behaviors_platform/CMakeLists.txt
- as2_hardware_drivers/as2_realsense_interface/package.xml
---
* Added test dependencies to `as2_platform_dji_osdk` and `as2_realsense_interface`
* Removed unused dependencies in `as2_behaviors_platform`
> fixing jenkins build failures

- as2_simulation_assets/as2_ign_gazebo_assets/models/hexrotor_base/hexrotor_base.sdf.jinja
| Issue(s) this addresses   | #319 |
---
* TF publish rate increase to 100hz in hexrotor model
* Bug fixed in Multicopter Control plugin name
> Hexrotor back to fly

- as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/models/object.py
| Issue(s) this addresses   | #324 |
---
* Look for objects in environment variable
> Spawn objects from gz resource path

- as2_behaviors/as2_behaviors_motion/follow_path_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_base.hpp
- as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_behavior.hpp
- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_behavior.hpp
- as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_base.hpp
- as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_behavior.hpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_base.hpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_behavior.hpp
- as2_core/include/as2_core/utils/tf_utils.hpp
- as2_core/src/utils/tf_utils.cpp
- as2_motion_controller/config/motion_controller_default.yaml
- as2_motion_controller/include/as2_motion_controller/controller_handler.hpp
- as2_motion_controller/src/controller_handler.cpp
Low latency frames support
---
| Issue(s) this addresses   | No issue in Main|
---
> low latency frames suppport

- as2_aerial_platforms/as2_platform_dji_osdk/include/dji_camera_handler.hpp
---
| Issue(s) this addresses   | #336  |
| Aerial platform tested on | DJI |
---
* Add topic `camera/source` to choose RGB or IR camera source
> Add camera change source topic

- as2_aerial_platforms/as2_platform_crazyflie/config/platform_config_file.yaml
- as2_aerial_platforms/as2_platform_crazyflie/include/as2_platform_crazyflie/crazyflie_platform.hpp
- as2_aerial_platforms/as2_platform_crazyflie/src/crazyflie_platform.cpp
| Issue(s) this addresses   | #340  |
| Aerial platform tested on | Crazyflie |
---
* Interface to LaserScan msg
---
* It might be interesting to extend it to PointCloud2 msgs
* Consider to create a new as2::Sensor that gathers both msg publishers
> Multi-ranger deck support

- as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_behavior.hpp
- as2_core/src/utils/tf_utils.cpp
---
| Issue(s) this addresses   |fix tf timeout param|
| Aerial platform tested on |Ignition |
---
> tf timeout param added to go to function plus hotfix

- as2_aerial_platforms/as2_platform_tello/include/tello_platform.hpp
- as2_aerial_platforms/as2_platform_tello/src/tello_platform.cpp
- as2_aerial_platforms/as2_platform_tello/tello/src/tello.cpp
---
| Aerial platform tested on | Tello |
---
* Uncomment video thread in Tello platform so image is sent to the camera topic
* Set publish rate to 30 hz
---
> Fix tello camera

- as2_msgs/CMakeLists.txt
- as2_msgs/msg/Geofence.msg
- as2_msgs/srv/GetGeofence.srv
- as2_msgs/srv/SetGeofence.srv
---
| Issue(s) this addresses   | #354  |
| ROS2 version tested on |Humble |
| Aerial platform tested on |Ignition, PX4 |
---
* Geofencing messages removed from as2_msgs
* When cloning geofencing node, you may need to clean as2_msgs and recompile because it could find the old binaries.
> Geofence messages removed from as2_msgs

- as2_core/include/as2_core/aerial_platform.hpp
- as2_core/src/aerial_platform.cpp
---
---
* Add node options with default value at aerial platform constructor.
> [as2_core] Add node options to aerial platform

- as2_motion_controller/plugins/pid_speed_controller/CMakeLists.txt
- as2_motion_controller/plugins/pid_speed_controller/include/pid_speed_controller/pid_speed_controller.hpp
- as2_motion_controller/plugins/pid_speed_controller/src/pid_speed_controller.cpp
---
---
* Update PID controller from v0.1 to v1.0:
- Change camelCase to snake_case.
- Change headers names
- Small fixes
* Update controller usage
- Remove unnecessary shared pointers to controllers
> [as2_motion_controller] Update PID controller dependence to v1.0

- as2_python_api/setup.py
| Issue(s) this addresses   | #372  |
---
* Added submodules to setup.py. It should fix issue with binaries
> [as2_python_api] Specifying subdirectories in setup.py

- as2_python_api/as2_python_api/modules/dummy_module.py
- as2_python_api/as2_python_api/test/profiling.py
- as2_python_api/as2_python_api/test/test_interpreter.py
| Issue(s) this addresses   | #374 |
---
* Moving test files to folder 
* Renaming test_module to dummy_module to avoid test conflict
* Fixing copyright test in profiling.py
> Moving test files to test folder

- as2_simulation_assets/as2_gazebo_classic_assets/scripts/run_sitl.sh
---
| ROS2 version tested on | (Humble) |
| Aerial platform tested on | (Gazebo classic 11) |
---
* Passes drone namespace so multiple drones can be spawned easily and have topics such as
/drone0/sensor_measurements/camera/
/drone1/sensor_measurements/camera/
> run_sitl.sh to pass drone namespace

- as2_simulation_assets/as2_ign_gazebo_assets/models/aruco_gate_1/aruco_gate_1.sdf
- as2_simulation_assets/as2_ign_gazebo_assets/models/aruco_gate_2/aruco_gate_2.sdf
---
---
* Fix aruco visualization in aruco_gate models in Ignition
* No documentation updates required
---
> Fix aruco visualization in aruco_gate models

- aerostack2/package.xml
- as2_aerial_platforms/as2_platform_ign_gazebo/package.xml
- as2_simulation_assets/as2_gazebo_assets/CHANGELOG.rst
- as2_simulation_assets/as2_gazebo_assets/hooks/resource_paths.sh
- as2_simulation_assets/as2_gazebo_assets/launch/launch_simulation.py
- as2_simulation_assets/as2_gazebo_assets/launch/world_bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridge.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/object.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
| Issue(s) this addresses   | #379 |
---
* Update old deps in package.xml
* Hooks path fixed for assets
* Changing naming in variables to not use ign anymore
> Cleaning remaining ign

- as2_aerial_platforms/as2_platform_dji_osdk/CMakeLists.txt
- as2_aerial_platforms/as2_platform_dji_osdk/package.xml
| Issue(s) this addresses   | #389 |
---
* Added libusb dependency
> Added libusb-dev dependency

- as2_core/src/utils/tf_utils.cpp
| Issue(s) this addresses   | #395 |
---
* Fix cpplint and uncrustify
> [as2_core] Fix linting

- codecov.yaml
* Removed extra `codecov.yaml`, since CI is using the `yml` one
> [CI] Removed extra codecov file

- as2_simulation_assets/as2_gazebo_assets/models/gimbal/model.config
- as2_simulation_assets/as2_gazebo_assets/models/gimbal/position_gimbal.sdf
- as2_simulation_assets/as2_gazebo_assets/models/gimbal/position_gimbal.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/gimbal/speed_gimbal.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/scripts/jinja_gen.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/custom_bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
- as2_simulation_assets/as2_gazebo_assets/src/gimbal_bridge.cpp
| Issue(s) this addresses   | #382 |
---
* Gimbal model is included from other file
* Gimbal model changed to use a nested model structure. Fixing bad tf tree
* Gz bridges updated to new names, allowing to work for gimbaled sensors
* Change `model_name` for `gimbal_name` in Aerial Platforms -> Gazebo
> [as2_gazebo_assets] Nested sdf model for gimbal and fixed TF tree

- as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
---
---
* Add a parameter to set if using global topics or add the namespace to the topic
> [as2_python_api] Add topic namespace with argument in mission interpreter

- as2_python_api/as2_python_api/behavior_actions/point_gimbal_behavior.py
- as2_python_api/as2_python_api/modules/point_gimbal_module.py
| Issue(s) this addresses   | #368 |
---
* New Behavior Client and Module for PointGimbal
> [as2_python_api] Point Gimbal behavior client

- as2_python_api/as2_python_api/modules/rtl_module.py
| Issue(s) this addresses   | #413 |
---
* New RTL module: performs GoTo to launch position and lands
> [as2_python_api] New RTL module

- as2_simulation_assets/as2_gazebo_assets/models/gimbal/position_gimbal.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/gimbal/speed_gimbal.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/point_lidar/point_lidar.sdf
| Issue(s) this addresses   | #407 |
---
* Using two samples at ray to visualize LaserScan on rviz2
* Drones with gimbal attached were not able to takeoff due to missing inertial in links
> Point gimbal and Gimbal Inertial links

- as2_aerial_platforms/as2_platform_dji_osdk/include/dji_camera_handler.hpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/include/point_gimbal_behavior/point_gimbal_behavior.hpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/src/point_gimbal_behavior.cpp
- as2_msgs/CMakeLists.txt
- as2_msgs/action/PointGimbal.action
- as2_msgs/msg/GimbalControl.msg
- as2_python_api/as2_python_api/behavior_actions/point_gimbal_behavior.py
- as2_simulation_assets/as2_gazebo_assets/src/gimbal_bridge.cpp
| Issue(s) this addresses   | #417 |
---
* New PointGimbal action
* Updated GimbalControl msg
* Update dji and gazebo platform with new msg changes
* Update gimbal bridge with new msg changes
* Update PointGimbal behavior server and client with new action
* Update documentation with changes in msg: Position mode is now 0 and fix on attitude type msg
> [as2_msgs] New point gimbal action

- as2_core/include/as2_core/utils/tf_utils.hpp
- as2_core/src/utils/tf_utils.cpp
---
| Aerial platform tested on | DJI |
---
* In TF utils, add a method for convert quaternion from current frame to target frame
> [as2_core] Add quaternion support for TF convert method

- as2_core/include/as2_core/utils/tf_utils.hpp
- as2_core/src/utils/tf_utils.cpp
---
| Issue(s) this addresses   |#423|
| Aerial platform tested on |None|
---
* Quaternion convert wrapped in try and catch
> quaternion convert wrapped in try and catch

- as2_behaviors/as2_behaviors_perception/CMakeLists.txt
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/CMakeLists.txt
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/include/point_gimbal_behavior/point_gimbal_behavior.hpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/launch/point_gimbal_behavior.launch.py
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/src/point_gimbal_behavior.cpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/src/point_gimbal_behavior_node.cpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/tests/CMakeLists.txt
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/tests/point_gimbal_gtest.cpp
- as2_core/include/as2_core/utils/frame_utils.hpp
- as2_core/src/utils/frame_utils.cpp
---
| Aerial platform tested on | Gazebo, DJI |
---
* Make Behavior Point Gimbal to look at a frame, set by the goal.
* Send commands in gimbal base link (rad angles)
> [as2_behaviors_perception] PointGimbalBehavior to use TF

- as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
- as2_state_estimator/plugins/ground_truth/include/ground_truth.hpp
- as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
---
| Issue(s) this addresses   |#428 #170|
| Aerial platform tested on |Gazebo, DJI_PSDK|
---
* Origin param available
* Now raw_odometry place map in take off position
* Code cleaned (not refactored)
* Refactor code
> 428 as2 state estimator raw odometry plugin should have a set gps origin

- as2_python_api/as2_python_api/modules/rtl_module.py
---
| Issue(s) this addresses   | #437 |
---
* Added feedback to rtl module
* Feedback references the (sub)module's feedback currently executing.
> Added feedback to rtl module

- as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
---
| Issue(s) this addresses   | #433 |
---
* Added try except in deserialize method
> added try except in deserialize method

- as2_aerial_platforms/as2_platform_tello/config/platform_default.yaml
- as2_aerial_platforms/as2_platform_tello/src/tello_platform.cpp
| Issue(s) this addresses   | #404 |
| Aerial platform tested on | Tello |
---
* Added missing parameter `sensor_freq`
* Default config file renamed to match the one used in launcher
* Add new project example with Tello
---
* Platform node still dying. Further tests needed.
```bash
$ ros2 launch as2_platform_tello tello_platform.launch.py namespace:=tello use_sim_time:=false platform_config_file:=config/platform.yaml
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2024-02-12-20-47-16-394332-gf66-129671
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [as2_platform_tello_node-1]: process started with pid [129698]
[as2_platform_tello_node-1] [INFO] …
```
> [as2_platform_tello] Missing param and new file name

- as2_behaviors/as2_behaviors_motion/go_to_behavior/plugins/go_to_plugin_position.cpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/src/go_to_behavior.cpp
---
| Issue(s) this addresses   | #440  |
---
> yaw fixed in frame other than earth

- as2_core/include/as2_core/sensor.hpp
- as2_core/src/sensor.cpp
- as2_core/tests/sensor_test.cpp
---
| Aerial platform tested on | as2_multirotor_simulator |
---
* Add a class GroundTruth to handler pose and twist ground truth publish
> [as2_core] Add GroundTruth to handler ground truth publish

- as2_aerial_platforms/as2_platform_tello/tello/src/socket_udp.cpp
---
| Aerial platform tested on | Tello |
---
* Warning in compilation fixed
```
/root/aerostack2_ws/src/aerostack2/as2_aerial_platforms/as2_platform_tello/tello/src/socket_udp.cpp:3:62: warning: unused parameter ‘bufferSize’ [-Wunused-parameter]
3 | SocketUdp::SocketUdp(const std::string& host, int port, uint bufferSize) {
|                                                         ~~~~~^~~~~~~~~~
```
---
> [fix] warning removed

- as2_core/as2_core/launch_param_utils.py
---
---
* Added launch utilities that allow users to set parameters via a configuration file and through parameters, following this order:
1. Default configuration file in the package config folder.
2. Custom configuration file specified in the launch command (e.g., config_file:=path/to/file.yaml).
3. Custom parameters specified in the launch command (e.g., param:=100).
* Example usage:
```
import as2_core.launch_param_utils as as2
def generate_launch_description():
"""Entrypoint."""
package_folder = get_package_share_directory('pkg_name')
custom_config_file = os.path.join(package_folder, 'config/custom_config_file.yaml') …
```
> [as2_core] Add launch params utils

- as2_simulation_assets/as2_gazebo_assets/CMakeLists.txt
- as2_simulation_assets/as2_gazebo_assets/hooks/resource_paths.dsv.in
- as2_simulation_assets/as2_gazebo_assets/hooks/resource_paths.sh
- as2_simulation_assets/as2_gazebo_assets/plugins/SuctionGripper.cc
- as2_simulation_assets/as2_gazebo_assets/plugins/SuctionGripper.hh
- as2_simulation_assets/as2_gazebo_assets/src/azimuth_bridge.cpp
- as2_simulation_assets/as2_gazebo_assets/src/gps_bridge.cpp
- as2_simulation_assets/as2_gazebo_assets/src/ground_truth_bridge.cpp
- as2_simulation_assets/as2_gazebo_assets/src/object_tf_broadcaster.cpp
---
| Aerial platform tested on | Gazebo,) |
---
* added compatibility with Gazebo Harmonic keeping compatibility with fortress
* No major documentation has to be done 
---
* Test the Suction Gripper plugin
> Gz harmonic support

- as2_core/include/as2_core/sensor.hpp
- as2_core/src/sensor.cpp
- as2_core/tests/sensor_test.cpp
---
| Aerial platform tested on | as2_multirotor_simulator, Gazebo |
---
*The gimbal sensor has been added, to incorporate it into TF and publish it via a topic.
*Three utility classes have been added:
- TFStatic: Adds methods for managing static transformations in TF.
- TFDynamic: Adds methods for managing dynamic transformations in TF.
- SensorData<T>: Adds methods for managing sensor data and its publication via a topic.
- GenericSensor: Adds utilities for managing the publication of data at a specific frequency.
Through composition and inheritance, different sensors can be added.
The Sensor, Camera, and GroundTruth classes all maintain the same …
> [as2_core] Refactor sensors and add gimbal sensor

- as2_simulation_assets/as2_gazebo_assets/src/gimbal_bridge.cpp
---
* Replaced ignition with gz
> [as2_gazebo_assets] Fix gimbal_bridge on Gazebo Harmonic

- as2_simulation_assets/as2_gazebo_assets/CMakeLists.txt
* TEMPORAL fix for CI running correctly,  
* src/as2_gazebo_assets/tests/test_models.py has been commented in CMakeLists.txt
> [as2_gazebo_assets] tests commented in CMAKE, fix ASAP

- .github/workflows/codecov_test.yaml
---
| ROS2 version tested on | (Humble, Other) |
| Aerial platform tested on | (Gazebo, Crazyflie, Tello, PX4, DJI, Multirotor Simulator, Other) |
---
---
> Merge main

- README.md
Dockerhub added to readme
We shall add this as a candidate installation.
> [docs] Readme with the dockerhub included

- .github/workflows/build_platforms_humble.yaml
---
* Added a strategy matrix in CI for parallelizing the platforms run
> [CI] matrix added to platforms build ci

- as2_aerial_platforms/as2_platform_multirotor_simulator/launch/as2_platform_multirotor_simulator.launch.py
- as2_aerial_platforms/as2_platform_multirotor_simulator/launch/as2_platform_multirotor_simulator_world.launch.py
- as2_behaviors/as2_behaviors_perception/detect_aruco_markers_behavior/launch/detect_aruco_markers_behavior_real_launch.py
- as2_behaviors/as2_behaviors_perception/detect_aruco_markers_behavior/launch/detect_aruco_markers_behavior_sim_launch.py
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/launch/point_gimbal_behavior.launch.py
- as2_core/as2_core/launch_param_utils.py
- as2_motion_controller/launch/controller_launch.py
- as2_user_interfaces/as2_keyboard_teleoperation/test/__test_flake8.py
- as2_user_interfaces/as2_keyboard_teleoperation/test/__test_pep257.py
---
| Issue(s) this addresses   | * |
---
* Flake8 tests pass
---
* Update keyboard to pass all Flake8 tests
> [aerostack2] Update launchers to Flake8

- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/object.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/world.py
…RCE_PATH
---
| Issue(s) this addresses   | #485 |
| Aerial platform tested on | Gazebo (Harmonic)|
---
* IGN_GAZEBO_RESOURCE_PATH changed to GZ_SIM_RESOURCE_PATH
* Gazebo Harmonic works now
> IGN_GAZEBO_RESOURCE_PATH changed to GZ_SIM_RESOURCE_PATH

- as2_python_api/as2_python_api/mission_interpreter/mission.py
- as2_simulation_assets/as2_gazebo_assets/CMakeLists.txt
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/entity.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/tests/test_models.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/world.py
| Issue(s) this addresses   | #469  |
---
* Tests restored
* Continue using Pydantic V1 features
* Using ForwardRef to work with pydantic==1.8
---
* Should migrate to Pydantic V2 in the near future
> [as2_gazebo_assets] Continue using Pydantic V1

- as2_cli/bash_utils/as2_build.bash
- as2_cli/bash_utils/as2_list.bash
- as2_cli/bash_utils/as2_test.bash
- docker/humble/Dockerfile
* AS2 list now also list python packages
* AS2 test now show the errrors without verbose
> [as2_cli] improvement in as2_list and as2_test

- as2_python_api/as2_python_api/behavior_actions/follow_reference_behavior.py
- as2_python_api/as2_python_api/behavior_actions/followpath_behavior.py
- as2_python_api/as2_python_api/behavior_actions/go_to_behavior.py
- as2_python_api/as2_python_api/behavior_actions/land_behavior.py
- as2_python_api/as2_python_api/behavior_actions/point_gimbal_behavior.py
- as2_python_api/as2_python_api/modules/follow_path_gps_module.py
- as2_python_api/as2_python_api/modules/follow_path_module.py
- as2_python_api/as2_python_api/modules/follow_reference_module.py
- as2_python_api/as2_python_api/modules/go_to_gps_module.py
- as2_python_api/as2_python_api/modules/go_to_module.py
- as2_python_api/as2_python_api/modules/land_module.py
- as2_python_api/as2_python_api/modules/point_gimbal_module.py
- as2_python_api/as2_python_api/modules/rtl_module.py
- as2_python_api/as2_python_api/modules/takeoff_module.py
---
| Issue(s) this addresses   | #378  |
---
* Behaviors call return the goal acceptance or rejection
* Update the docstring of methods to include return information.
> [as2_python_api] Add goal accepted/rejected return when call behavior method

- docker/humble/Dockerfile
---
| Issue(s) this addresses   |- |
---
* Fix docker pysimplegui installation
> [aerostack2] Fix pysimplegui version in docker

- as2_msgs/CMakeLists.txt
- as2_msgs/package.xml
---
| Issue(s) this addresses   | #490  |
| Aerial platform tested on | Gazebo, Multirotor Simulator |
---
* Add lint tests to as2_msgs
Note: Lint common can not be use since cpplint and uncrustify need cpp files to pass
> [as2_msgs] Add lint tests

- as2_motion_controller/CMakeLists.txt
- as2_motion_controller/include/as2_motion_controller/controller_manager.hpp
- as2_motion_controller/plugins/differential_flatness_controller/CMakeLists.txt
- as2_motion_controller/plugins/differential_flatness_controller/tests/CMakeLists.txt
- as2_motion_controller/plugins/pid_speed_controller/CMakeLists.txt
- as2_motion_controller/plugins/pid_speed_controller/tests/CMakeLists.txt
- as2_motion_controller/plugins/pid_speed_controller/tests/pid_speed_controller_gtest.cpp
- as2_motion_controller/src/controller_manager.cpp
- as2_motion_controller/tests/as2_motion_controller_gtest.cpp
---
---
- Fixing library generation, which wasn't being done properly.
- Adding a gtest for each plugin loading.
> [as2_motion_controller] Fix library exports and add simple gtest

- as2_motion_controller/config/motion_controller_default.yaml
- as2_motion_controller/launch/controller_launch.py
---
| Issue(s) this addresses   | #511  |
---
- Updating the launcher using as2_core launch param utils.
> [as2_motion_controller] Update launch using as2_core launch params utils

- as2_aerial_platforms/as2_platform_multirotor_simulator/CMakeLists.txt
- as2_aerial_platforms/as2_platform_multirotor_simulator/launch/as2_platform_multirotor_simulator.launch.py
- as2_aerial_platforms/as2_platform_multirotor_simulator/tests/as2_platform_multirotor_simulator_fly_gtest.cpp
---
---
- Change gtest to use as2 core mock
- Clean CMakeLists.txt
- Clean launcher
> [as2_platform_multirotor_simulator] Change gtest to use as2 core mock

- README.md
Test CI changes for accepting PRs from forked repos
> Validation CI workflows for external 

- docker/humble_gzharmonic/dockerfile
---
---
* Dockerfile for working with Gazebo Harmonic simulator.
---
> dockerfile for working with gz harmonic

- as2_python_api/as2_python_api/behavior_actions/behavior_handler.py
---
| Issue(s) this addresses   | #534 ) |
| ROS2 version tested on | (Humble) |
| Aerial platform tested on | (Other) |
---
Now the status of the behaviors in python API gets updated immediately without waiting for the subscription.
A new method is_running() is also implemented for easing the asynchronous mission scripts.
* Examples using the python API for mission shall be further documented, including blocking and not blocking calls
> [fix] Behavior Status updated after call methods correctly

- as2_simulation_assets/as2_gazebo_assets/launch/drone_bridges.py
- as2_simulation_assets/as2_gazebo_assets/launch/launch_simulation.py
- as2_simulation_assets/as2_gazebo_assets/launch/object_bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/utils/launch_exception.py
---
---
* Support yaml files for gazebo world configuration
> [as2_gazebo_assets] Support yaml files for gazebo world configuration

- as2_user_interfaces/as2_alphanumeric_viewer/include/as2_alphanumeric_viewer/alphanumeric_viewer.hpp
- as2_user_interfaces/as2_alphanumeric_viewer/src/alphanumeric_viewer.cpp
---
| Issue(s) this addresses   |#549|
---
* Dummy detector for battery range [0,1] or [0,100]
* Defaults to [0,1] until a greater value arrives.
> [as2_alphanumeric_viewer] Battery status problem fixed

- as2_utilities/as2_external_object_to_tf/launch/as2_external_object_to_tf_launch.py
---
* Add config file as launch argument
* Use env var as default namespace
> Fix as2_external_object_to_tf_launch.py

- as2_state_estimator/plugins/ground_truth/config/plugin_default.yaml
- as2_state_estimator/plugins/ground_truth/include/ground_truth.hpp
---
---
* Change ignition to gazebo parameter name
---
* Update projects with gazebo simulation with this parameter name
> [as2_state_estimator] Change gazebo tf parameter name

- docker/humble/Dockerfile
- docker/humble_vnc/dockerfile
---
| Issue(s) this addresses   | #451 |
---
* Docker replace pysimplegui for PySimpleGUI-4-foss
> [aerostack2] Docker replace pysimplegui for PySimpleGUI-4-foss

- as2_utilities/as2_external_object_to_tf/launch/as2_external_object_to_tf_launch.py
---
| Issue(s) this addresses   | #563 |
| Aerial platform tested on ||
---
> [as2_external_object_to_tf] default config file within the node

- as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface.cpp
- as2_hardware_drivers/as2_usb_camera_interface/config/usb_camera_interface_default.yaml
---
| Issue(s) this addresses   | -  |
---
* Fix timestamp using ROS 2 node one
> [as2_realsense_interface] Fix timestamp

- as2_core/src/sensor.cpp
---
---
* Read encoding from ROS 2 param
> [as2_core] AS2 Sensors Camera read encoding from ROS param

- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
---
---
* Fix flake8 test failures from main.
---
> [as2_gazebo_assets] Fix for flake8.

- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/config/teleop_values_config.yaml
- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
- as2_user_interfaces/as2_keyboard_teleoperation/setup.py
---
| Issue(s) this addresses   |#546 #542 #575 #543 |
---
* Can load namespace list with ',' ':' and ' ' 
* ROS 2 parameters config file working
* Changed behavior of speed mode
* Can load namespace list with ',' ':' and ' ' 
* ROS 2 parameters config file working
>  [as2_keyboard_teleoperation] launcher improved to load namespace with different dividers, config file and speed behavior

- as2_map_server/CMakeLists.txt
- as2_map_server/LICENSE
- as2_map_server/include/as2_map_server/map_server.hpp
- as2_map_server/include/as2_map_server/plugin_base.hpp
- as2_map_server/launch/map_server.launch.py
- as2_map_server/package.xml
- as2_map_server/plugins.xml
- as2_map_server/plugins/mapping_2d/config/plugin_default.yaml
- as2_map_server/plugins/mapping_2d/include/mapping_2d.hpp
- as2_map_server/plugins/mapping_2d/src/mapping_2d.cpp
- as2_map_server/src/map_server.cpp
- as2_map_server/src/map_server_node.cpp
- as2_map_server/tests/CMakeLists.txt
- as2_map_server/tests/map_server_gtest.cpp
| Issue(s) this addresses   | #488  |
---
**TBD**
**TBD**
---
**TBD**
> [as2_map_server] First implementation

- as2_python_api/as2_python_api/drone_interface.py
- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/drone_interface_gps.py
- as2_python_api/as2_python_api/drone_interface_teleop.py
| Issue(s) this addresses   | #595 |
---
* Added new class argument to select spin rate
---
> [as2_python_api] Added class argument spin rate

- as2_python_api/as2_python_api/drone_interface.py
- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/drone_interface_gps.py
- as2_python_api/as2_python_api/drone_interface_teleop.py
---
| Aerial platform tested on | Gazebo, Multirotor Simulator |
---
* Fix using spin rate as a rate and not as an time interval
> [as2_python_api] Fix using spin rate as a rate and not as an time interval

- as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie_viz.sdf
| Issue(s) this addresses   | #598 |
---
* Model adapted to open at RViz
To merge after #590
> [as2_gazebo_assets] Added crazyflie viz

- as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf
- as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja
---
---
* Add IMU sensor
* Use quadrotor_base template
* Improve internal controller
> [as2_gazebo_assets] Improve crazyflie model

- as2_utilities/as2_external_object_to_tf/config/external_objects.yaml
- as2_utilities/as2_external_object_to_tf/include/as2_external_object_to_tf/as2_external_object_to_tf.hpp
- as2_utilities/as2_external_object_to_tf/launch/as2_external_object_to_tf_launch.py
- as2_utilities/as2_external_object_to_tf/src/as2_external_object_to_tf.cpp
---
| Issue(s) this addresses   |#602|
---
* Fix mocap source data
> [as2_external_object_tf_tf] fix mocap source data

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/config/teleop_values_config.yaml
- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
---
| Issue(s) this addresses   | #542 |
---
* use_sim_time and verbose from config file
* ability to configure speed and pose frame id
* ability to configure initial mode
* Update documentation with new config file
> [as2_keyboard_teleoperation] as2 keyboard teleoperation add ros 2 parameters

- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/service_clients/arming.py
- as2_python_api/as2_python_api/service_clients/offboard.py
- as2_python_api/as2_python_api/service_clients/service_handler.py
---
---
* Return bool service response when using ServiceBoolHandler: arm, offboard and manual
* Add manual method to disable offboard mode
* Now if service return succes=False, it doesn't throw an exception, but return failure, so user can manage it
> [as2_python_api] Return service response

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
- as2_user_interfaces/as2_keyboard_teleoperation/test/test_copyright.py
- as2_user_interfaces/as2_keyboard_teleoperation/test/test_flake8.py
- as2_user_interfaces/as2_keyboard_teleoperation/test/test_pep257.py
| Issue(s) this addresses   | #490 |
---
* Ament lint compliance to all files in package
> [as2_keyboard_teleop] ament lint compliance

- as2_python_api/as2_python_api/behavior_actions/navigate_to_behavior.py
- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/modules/navigate_to_module.py
- as2_python_api/as2_python_api/service_clients/arming.py
- as2_python_api/as2_python_api/service_clients/offboard.py
- as2_python_api/as2_python_api/service_clients/service_handler.py
| Issue(s) this addresses   | #490 |
---
* Flake8 and PEP257 compliance
> [as2_python_api] Ament_lint compliance

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/config/teleop_values_config.yaml
---
| Issue(s) this addresses   | #623 |
---
* drone_frequency param added
> [as2_keyboard_teleoperation] drone_frequency param added

- as2_core/as2_core/declare_launch_arguments_from_config_file.py
- as2_core/as2_core/launch_configuration_from_config_file.py
- as2_core/as2_core/launch_param_utils.py
| Issue(s) this addresses   | #511 |
---
* Support for ROS2 yaml files which may content repeated keys
* New entry at documentation explaining how to use these classes
> [as2_core] Extended params utils

- as2_motion_controller/config/motion_controller_default.yaml
> [as2_motion_controller] Update motion_controller_default.yaml typo

- as2_utilities/as2_external_object_to_tf/launch/as2_external_object_to_tf_launch.py
---
| Aerial platform tested on ||
---
> [as2_external_object_to_tf] quick fix flake8

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/config/teleop_values_config.yaml
- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
---
| Issue(s) this addresses   | #609 |
---
* default behaviors extended from argument
> [as2_keyboard_teleoperation] extend default behaviors from argument

- .github/workflows/build-humble.yaml
- .github/workflows/codecov_test.yaml
- aerostack2/package.xml
---
---
Add the followings packages:
* as2_behaviors_path_planning
* as2_geozones
* as2_rviz_plugins
* as2_visualization
Sort them using `as2 list`
* Add as2_python_api to workflows
> [aerostack2] Update package dependencies and CI with new aerostack2 packages

- as2_user_interfaces/as2_keyboard_teleoperation/launch/as2_keyboard_teleoperation_launch.py
---
| Issue(s) this addresses   |#639|
---
* Teleop adapted to new utils version
> [as2_keyboard_teleoperation] now context is modified manually from generated config file

- as2_msgs/package.xml
---
* Added a missing dependency in as2_msgs pkg
> [fix] add sensor msgs dependency

- as2_python_api/as2_python_api/mission_interpreter/mission_stack.py
- as2_python_api/as2_python_api/test/test_mission_stack.py
| Issue(s) this addresses   | #649 |
---
* [bug] fix when done dequeue is empty
* [feat] new insert method for single items or item lists
* [feat] add method changed to accept item lists
* [feat] new previous_item method
* [test] new test for mission stack
None
---
* Interpreter needs update to new stack methods
> [as2_python_api] New MissionStack methods

- as2_python_api/as2_python_api/drone_interface.py
- as2_python_api/as2_python_api/drone_interface_base.py
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
| Issue(s) this addresses   | #651 |
---
* Executor can be chosen from `DroneInterfaceBase` and `MissionInterpreter` constructors
-
---
-
> [as2_python_api] Choose executor from DroneInterfaceBase constructor

- as2_aerial_platforms/as2_platform_multirotor_simulator/package.xml
- as2_behaviors/as2_behaviors_path_planning/package.xml
- as2_map_server/package.xml
- as2_state_estimator/package.xml
- as2_user_interfaces/as2_alphanumeric_viewer/package.xml
- as2_user_interfaces/as2_visualization/as2_rviz_plugins/package.xml
- as2_user_interfaces/as2_visualization/as2_visualization/package.xml
- as2_utilities/as2_external_object_to_tf/package.xml
- as2_utilities/as2_geozones/package.xml
| Issue(s) this addresses   | #653 |
---
* chore: license tag to `<license>BSD-3-Clause</license>`
* chore: maintainer tag to `<maintainer email="cvar.upm3@gmail.com">CVAR-UPM</maintainer>`
> [aerostack2] Maintainer and license tags update

- as2_msgs/CMakeLists.txt
- as2_msgs/msg/ControlMode.msg
- as2_user_interfaces/as2_alphanumeric_viewer/src/alphanumeric_viewer.cpp
---
---
* Remove ACEL control mode as not exits
* Automate as2_msgs files in CMakeLists.txt
> [as2_msgs] Remove ACEL control mode as not extis

- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/CMakeLists.txt
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/launch/composable_generate_polynomial_trajectory_behavior.launch.py
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/launch/generate_polynomial_trajectory_behavior_launch.py
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/tests/generate_polynomial_trajectory_behavior_gtest.cpp
- as2_core/include/as2_core/names/topics.hpp
---
---
* Add two parameters:
```yaml
sampling_n: 1 # Number of sampling of the trajectory
sampling_dt: 0.01 # Time between each sampling
```
* Array of setpoints with size _sampling_n_ is send with evaluation delta time _sampling_dt_
* Use as2_core launch utils and a config file
> [as2_behaviors_trajectory_generation] Send array of setpoints 

- as2_motion_controller/plugins/differential_flatness_controller/tests/differential_flatness_controller_gtest.cpp
---
---
* Add gtest for differential_flatness_controller plugin
> [as2_motion_controller] Add differential_flatness_controller_gtest

- as2_motion_controller/CMakeLists.txt
- as2_motion_controller/plugins.xml
---
---
* Export headers and libraries correctly for use in other packages
* Fix typo in PID plugin description
> [as2_motion_controller] Export headers and libraries

- as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp
…form
---
---
* Fix as2_platform_multirotor_simulator ground thrust twist frame transform
> [as2_platform_multirotor_simulator] Fix as2_platform_multirotor_simulator ground thrust twist frame

- as2_simulation_assets/as2_gazebo_assets/models/gate/gate.sdf
- as2_simulation_assets/as2_gazebo_assets/models/gate/model.config
---
* Submesh not needed and it might be confusing when creating new models
> [as2_gazebo_assets] Remove submesh in gate model

- as2_python_api/as2_python_api/behavior_actions/traj_generation_behavior.py
- as2_python_api/as2_python_api/modules/traj_generation_module.py
| Issue(s) this addresses   | #704 |
---
* New `TrajGenerationBehavior` and `TrajGenerationModule`
> [as2_python_api] New trajectory generation module

- as2_msgs/msg/Acro.msg
---
---
* Added ACRO message to Aerostack2
---
> [as2_msgs] ACRO message 

- as2_aerial_platforms/as2_platform_gazebo/config/control_modes_acro.yaml
- as2_aerial_platforms/as2_platform_gazebo/include/as2_platform_gazebo/as2_platform_gazebo.hpp
- as2_aerial_platforms/as2_platform_gazebo/launch/platform_gazebo_launch.py
- as2_aerial_platforms/as2_platform_gazebo/src/as2_platform_gazebo.cpp
- as2_aerial_platforms/as2_platform_gazebo/tests/as2_platform_gazebo_gtest.cpp
---
---
* Gazebo Platform adapted to suscribe to and publish ACRO commands.
---
> [as2_platform_gazebo] Platform Gazebo ACRO commands publisher

- as2_simulation_assets/as2_gazebo_assets/models/grayscaled_camera/grayscaled_camera.jinja
- as2_simulation_assets/as2_gazebo_assets/models/grayscaled_camera/grayscaled_camera.sdf
- as2_simulation_assets/as2_gazebo_assets/models/grayscaled_camera/grayscaled_camera.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/grayscaled_camera/model.config
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
---
---
* Gazebo grayscale camera model added.
---
> [as2_gazebo_assets] Grayscaled camera model added.

- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
---
---
* Add controller type parameter to arm bridge.
* Add bridge call for velocity and acro controllers.
---
> [as2_gazebo_assets] Add different controller topics to arm bridge

- as2_simulation_assets/as2_gazebo_assets/models/crazyflie/crazyflie.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/px4vision/px4vision.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/models/x500/x500.sdf.jinja
---
* Fixes issue that drone models were not flying introduced in #714
> [as2_gazebo_assets] Restore Multicopter plugin filename and parameters

- as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_base.hpp
- as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_behavior.hpp
- as2_behaviors/as2_behaviors_motion/follow_path_behavior/src/follow_path_behavior.cpp
- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
- as2_behaviors/as2_behaviors_motion/follow_reference_behavior/src/follow_reference_behavior.cpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_base.hpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_behavior.hpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/src/go_to_behavior.cpp
- as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_base.hpp
- as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_behavior.hpp
- as2_behaviors/as2_behaviors_motion/land_behavior/src/land_behavior.cpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_base.hpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_behavior.hpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/src/takeoff_behavior.cpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/include/point_gimbal_behavior/point_gimbal_behavior.hpp
- as2_behaviors/as2_behaviors_perception/point_gimbal_behavior/src/point_gimbal_behavior.cpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
- as2_core/include/as2_core/utils/tf_utils.hpp
- as2_core/src/utils/tf_utils.cpp
- as2_core/tests/tf_utils_gtest.cpp
- as2_motion_controller/include/as2_motion_controller/controller_handler.hpp
- as2_motion_controller/src/controller_handler.cpp
---
---
* Read `tf_timeout_threshold` param from `TfHandler`, instead each node declare and manage it
* Template tf utils methods
* Add tf utils gtest
> [as2_core] Read timeout from TfHandler

- as2_behaviors/as2_behaviors_perception/detect_aruco_markers_behavior/include/detect_aruco_markers_behavior/detect_aruco_markers_behavior.hpp
- as2_behaviors/as2_behaviors_perception/detect_aruco_markers_behavior/src/detect_aruco_markers_behavior.cpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
- as2_msgs/msg/PoseStampedWithIDArray.msg
---
---
* Modify trajectory waypoints using PoseStampedWithID Array
> [as2_behaviors_trajectory_generation] Modify trajectory waypoints using PoseStampedWithID Array

- as2_python_api/as2_python_api/behavior_actions/followpath_behavior.py
- as2_python_api/as2_python_api/behavior_actions/traj_generation_behavior.py
---
---
* Fix follow path and traj generation behaviors get path checkers
> [as2_python_api] Fix follow path and traj generation behaviors get path checkers

- as2_state_estimator/plugins/raw_odometry/config/plugin_default.yaml
- as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
---
---
* Add earth to map transform using ROS 2 params in raw odometry plugin
> [as2_state_estimator] Add earth to map transform using ROS 2 params in raw odometry plugin

- as2_python_api/as2_python_api/behavior_actions/trajectory_generation_behavior.py
- as2_python_api/as2_python_api/modules/trajectory_generation_module.py
---
---
* Rename trajectory generation behavior and class name
> [as2_python_api] Rename trajectory generation behavior and class name

- as2_map_server/CMakeLists.txt
- as2_map_server/package.xml
- as2_map_server/plugins.xml
- as2_map_server/plugins/point_cloud2occ_grid/CMakeLists.txt
- as2_map_server/plugins/point_cloud2occ_grid/config/plugin_default.yaml
- as2_map_server/plugins/point_cloud2occ_grid/launch/point_cloud2occ_grid-map_server.launch.py
| Issue(s) this addresses   | #736 |
---
* New plugin `point_cloud2occ_grid`
> [as2_map_server] Added point_cloud2occ_grid plugin

- as2_user_interfaces/as2_visualization/as2_visualization/launch/as2_visualization.launch.py
---
---
* Enable the use of custom models from GZ_SIM_RESOURCE_PATH for visualize the drone in RViz
> [as2_visualization] Enable the use of custom models from GZ_SIM_RESOURCE_PATH

- as2_map_server/CMakeLists.txt
- as2_map_server/package.xml
- as2_map_server/plugins.xml
- as2_map_server/plugins/depth2occ_grid/config/plugin_default.yaml
- as2_map_server/plugins/point_cloud2occ_grid/CMakeLists.txt
- as2_map_server/plugins/point_cloud2occ_grid/config/plugin_default.yaml
- as2_map_server/plugins/point_cloud2occ_grid/launch/point_cloud2occ_grid-map_server.launch.py
- as2_map_server/plugins/scan2occ_grid/config/plugin_default.yaml
- as2_map_server/plugins/scan2occ_grid/include/scan2occ_grid.hpp
- as2_map_server/plugins/scan2occ_grid/src/scan2occ_grid.cpp
---
* Replace `get_middle_points` method with `bresenham_line` algorithm
* Add `hit_confidence` and `miss_confidence` ROS parameters
* Install library headers to create plugins from outside the package
> [as2_map_server] Bresenham line algorithm and new ros parameters

- as2_core/as2_core/launch_configuration_from_config_file.py
---
| Issue(s) this addresses   | #744|
| ROS2 version tested on |Humble |
| Aerial platform tested on |DJI_PSDK |
---
* Changed list for List from typing in launch utils.
> #744 Changed list for List from typing in launch utils.

- as2_motion_controller/launch/controller_launch.py
- as2_python_api/as2_python_api/mission_interpreter/mission.py
- as2_python_api/as2_python_api/shared_data/gps_data.py
- as2_python_api/as2_python_api/shared_data/orientation_data.py
- as2_python_api/as2_python_api/shared_data/platform_info_data.py
- as2_python_api/as2_python_api/shared_data/pose_data.py
- as2_python_api/as2_python_api/shared_data/position_data.py
- as2_python_api/as2_python_api/shared_data/twist_data.py
- as2_state_estimator/launch/state_estimator_launch.py
---
| Issue(s) this addresses   |#747|
| Aerial platform tested on |DJI_PSDK|
---
* Fixed python3.8 non friendly typings
> #747 fixed python3.8 non friendly typings

- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
---
| Aerial platform tested on | Gazebo, Multirotor Simulator |
---
* Control debug using ROS 2 params
* Add end waypoint in horizon publish
* Add path waypoints publish
* Each one can be disable setting topic to empty string
> [as2_behaviors_trajectory_generation] Improve debug

- as2_behaviors/as2_behaviors_motion/follow_path_behavior/plugins/follow_path_plugin_trajectory.cpp
- as2_behaviors/as2_behaviors_motion/go_to_behavior/plugins/go_to_plugin_trajectory.cpp
- as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_trajectory.cpp
- as2_behaviors/as2_behaviors_motion/takeoff_behavior/plugins/takeoff_plugin_trajectory.cpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
- as2_msgs/action/GeneratePolynomialTrajectory.action
- as2_python_api/as2_python_api/behavior_actions/trajectory_generation_behavior.py
---
| Aerial platform tested on | Gazebo, Multirotor Simulator |
---
* Change goal msgs. Now each waypoint has its own frame_id
* Change motion behaviors trajectory plugins to use new goal
* Change trajectory generation python module to use new goal
> [as2_behaviors_trajectory_generation] Enable trajectory generation goal in differents frames_id

- as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
---
---
* Fix `tf_handler` instantiation in plugin base
> [as2_state_estimator] Fix tf_handler instantiation in plugin base

- as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
- as2_state_estimator/launch/raw_odometry_ground_truth_fuse.launch.py
- as2_state_estimator/plugins/raw_odometry/CMakeLists.txt
- as2_state_estimator/plugins/raw_odometry/config/ground_truth_fuse.yaml
- as2_state_estimator/plugins/raw_odometry/config/plugin_default.yaml
- as2_state_estimator/plugins/raw_odometry/include/ground_truth_fuse.hpp
- as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
- as2_state_estimator/plugins/raw_odometry/src/ground_truth_fuse_node.cpp
---
---
* Add ground truth and odometry fuse node, subscribing to `sensor_measurement/odom` and `ground_truth/pose` / `mocap_rigid_bodies` topics.
* It update this transform in TF tree at a certain frequency
> [as2_state_estimator] Add ground truth and odometry fuse node

- as2_msgs/msg/MissionUpdate.msg
- as2_python_api/as2_python_api/mission_interpreter/mission.py
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
- as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
- as2_python_api/as2_python_api/test/test_interpreter.py
---
| Issue(s) this addresses   | #758  |
---
* Manage multiples missions loading
* Update mission msg removing abort and jump_to (replaced by next_item)
> [as2_python_api] Mission Interpreter improvements using multiples missions ids

- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
---
---
* New methods to compute the errors between map and odom frame
* New method to update the transform of the odom frame and update the trajectory
* Added new parameter to set the thresholds to compute the errors between frames
* Added new parameter to set the thresholds to compute the face next reference yaw
---
> [as2_behaviors_trajectory_generation] Update the transform between map and odom to update the trajectory

- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
---
---
* Fix setpoints evaluation, avoiding last setpoint storage for internal trajectory generator as current setpoint
> [as2_behaviors_trajectory_generation] Fix setpoints evaluation

- as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp
---
---
* Fix imu accelerometer read
> [as2_platform_multirotor_simulator] Fix imu read

- as2_hardware_drivers/as2_usb_camera_interface/config/config_file_default.yaml
- as2_hardware_drivers/as2_usb_camera_interface/include/as2_usb_camera_interface/as2_usb_camera_interface.hpp
- as2_hardware_drivers/as2_usb_camera_interface/src/as2_usb_camera_interface.cpp
---
---
* Enable arducam support
> [as2_behaviors_perception] Support arducam

- as2_state_estimator/launch/ground_truth_odometry_fuse_state_estimator.launch.py
- as2_state_estimator/plugins/ground_truth_odometry_fuse/config/plugin_default.yaml
- as2_state_estimator/plugins/ground_truth_odometry_fuse/include/ground_truth_odometry_fuse.hpp
---
| Aerial platform tested on | Betaflight |
---
* Self localization is published at odometry callback
* Add plugin launcher
> [as2_state_estimator] Replace timer for odometry callback in ground_truth_odometry_fuse

- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
- as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
---
| Aerial platform tested on |  Multirotor Simulator |
---
* Added a new parameter wp_close_threshold to not modify a waypoint if the estimated time to reach it is close to the actual time.
> [as2_behaviors_trajectory_generation] Modify a wp

- as2_state_estimator/plugins/ground_truth_odometry_fuse/config/plugin_default.yaml
---
---
* Fix default parameter
> [as2_state_estimator] Fix odom topic default parameter in ground_truth_odometry_fuse plugin

- as2_behaviors/as2_behavior/include/as2_behavior/__detail/behavior_server__class.hpp
- as2_behaviors/as2_behavior/include/as2_behavior/__impl/behavior_server__impl.hpp
---
| Issue(s) this addresses   | #779  |
---
* Implement modify service on behaviors
> [as2_behavior] Fix modify implementation on behaviors

- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/drone_manager.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
- as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
---
| Issue(s) this addresses   | No issue in particular |
---
This PR enables the possibility of commanding the drone with as2_keyboard_teleoperation in body pose. In this mode, the position controller uses a target position that is projected based on orientation of the drone. In that way, the manual navigation is simplified since the user does not need to be aware of any absolute (e.g. earth) coordinates to command the drone.
* Added new button in as2_keyboard_teleoperation for "Body Pose Mode"
* Added new functionality for "Body Pose Mode" to project the target position relative to the drone orientation (body pose)
* In Body Pose Mode the user is able …
> Body Pose for Position Control in Keyboard Teleoperation

- as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
---
| Aerial platform tested on | DJI |
---
*  Fix GPS Origin RCLCPP Info
> [as2_state_estimator] In Raw Odometry Plugin, fix GPS Origin Info

- as2_behaviors/as2_behaviors_path_planning/plugins/a_star/include/a_star.hpp
- as2_behaviors/as2_behaviors_path_planning/plugins/a_star/src/a_star.cpp
---
* Parameter updated to new name
> [as2_behaviors_path_planning] Fix parameter name mismatch

- as2_python_api/as2_python_api/behavior_actions/behavior_handler.py
- as2_python_api/as2_python_api/tools/utils.py
---
| Aerial platform tested on |Multirotor Simulator |
---
* Changed modify service type in behavior handler to match send goal service type in behavior client 
* Re-implemented modify method in behavior handler to cast action goal messages to send goal messages of the corresponding action. (E.g: from FollowPath.Goal to FolloPath_SendGoal)
* Tested in GoTo and FollowPath behaviors
* No documentation changes required
---
> [as2_python_api] Using goal in behavior handler modify service

- as2_python_api/as2_python_api/behavior_actions/behavior_handler.py
- as2_python_api/as2_python_api/mission_interpreter/mission.py
- as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
- as2_python_api/as2_python_api/mission_interpreter/mission_stack.py
- as2_python_api/as2_python_api/modules/go_to_module.py
- as2_python_api/as2_python_api/modules/module_base.py
- as2_python_api/as2_python_api/test/test_interpreter.py
- as2_python_api/as2_python_api/tools/utils.py
---
---
* Enabled modify via module for the GoToBehavior
* Added modify functionality for pending and current mission items in Mission Interpreter
---
* Implement modify method on other modules and uncomment abstract method in module base
> Mission interpreter mission modification

- as2_user_interfaces/as2_visualization/as2_visualization/as2_visualization/viz_parsing.py
---
| Issue(s) this addresses   | #793  |
---
* Fixed topic params instantiation with no arguments.
---
> Correctly fixed TopicParams instantiation

- as2_msgs/msg/UInt16MultiArrayStamped.msg
---
---
* Add Uint16 Multi Array Stamped message
---
> Add Uint16 Multi Array Stamped msgs

- as2_simulation_assets/as2_gazebo_assets/models/rgbd_camera/rgbd_camera.sdf
- as2_simulation_assets/as2_gazebo_assets/models/rgbd_camera/rgbd_camera.sdf.jinja
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py
- as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
---
| Issue(s) this addresses   | #807 |
---
* Modified assets to be able to load multi camera sensor
* Added new specific depth camera info interface
> 807-Ability to load single sensor with multiple cameras

- as2_map_server/plugins/point_cloud2occ_grid/launch/point_cloud2occ_grid-map_server.launch.py
---
| Issue(s) this addresses   | #815  |
---
* Fix param name `cloud_in`
> [fix] cloud_in param name
